### ISSUE TITLE
link to pxd files so users can easier look up all wrapped methods

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-docs#107]
e.g., put a link like "See all wrapped method definitions."

**Comment by timosachsenberg** [comment]
or find a better way (e.g., via sphinx)

**Comment by oliveralka** [comment]
e.g. https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html

**Comment by jpfeuffer** [comment]
Problem: pxds need to be available first. -> We need CI that pushes a fresh pyopenms wheel whenever there are updates.

**Comment by tapaswenipathak** [comment]
Can this be done rn?

**Comment by timosachsenberg** [comment]
let's move this a bit down the priority list

**Comment by jpfeuffer** [comment]
We have a barebones apidoc now. I agree on low priority

**Comment by timosachsenberg** [comment]
solved via api
