### ISSUE TITLE
Separate mixed code blocks in documentation

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#138]
Especially in the introduction there are often core blocks with both python code and in the next line the output.
This should be avoided for binder.

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/pyopenms-extra/blob/master/docs/source/datastructures.rst#lc-msms-experiment

**Comment by timosachsenberg** [comment]
From notebook is fine I guess. Would we get a failing action / step then?

**Comment by jpfeuffer** [comment]
Yes failing step. You can decide what to do with it. Stop run? Upload logs? Continue?

**Comment by timosachsenberg** [comment]
can we post this to cdash?
