### ISSUE TITLE
Add link to jupyter notebook as well (e.g., next to binder button)

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-docs#141]
scikit learn does it like that and it might be useful

**Comment by jpfeuffer** [comment]
can you show where they do this?

**Comment by timosachsenberg** [comment]
https://scikit-learn.org/stable/auto_examples/release_highlights/plot_release_highlights_1_0_0.html at the bottom

**Comment by tapaswenipathak** [comment]
Should this be done with a higher priority?

**Comment by timosachsenberg** [comment]
low priority is fine
