### ISSUE TITLE
add launch with Colab Button

### ISSUE THREAD

**Issue by rahul799** [OpenMS/pyopenms-docs#144]
It will be good to have Launch with Google Colab button similar to launch with binder option.

**Comment by timosachsenberg** [comment]
In principle linking like this:
```
https://colab.research.google.com/github/OpenMS/pyopenms-extra/blob/master%2Bipynb/docs/source/chromatographic_analysis.ipynb
```
already works.
What is missing is the installation of requirements (in binder done via requirements.txt)

**Comment by timosachsenberg** [comment]
hmm not great ...

**Comment by jpfeuffer** [comment]
You can conditionally execute: https://stackoverflow.com/questions/53581278/test-if-notebook-is-running-on-google-colab

**Comment by tapaswenipathak** [comment]
What is(/are) the remaining todo(s)?

**Comment by jpfeuffer** [comment]
This is done. Could use some improvements on how to install the nightly versions but this is tracked in another issue. We probably should test and use our own new pypi repo.
