### ISSUE TITLE
Double-check case sensitivity of anchor links

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#147]
Because the case sensitivity might be different between RST and ipynb (stricter).

E.g. (Peptide identification section)[#peptideidentification] to (Peptide identification section)[#PeptideIdentification]

**Comment by tapaswenipathak** [comment]
@greengypsy: can you check if there is existing documentation for this? If not, add and close?

**Comment by matteopilz** [comment]
The class & function references are also not working now, how should we do this?

**Comment by jpfeuffer** [comment]
You mean in ipynb? It never worked. ipynb has no knowledge about the API documentation. We could only link back to the readthedocs page. Could be done with another custom pandoc "plugin" that looks for :py:class: roles during conversion and treats them specially.

**Comment by matteopilz** [comment]
Yes, in ipynb. It probably wasn't mentioned before, because we only had a few of them. I will look into pandoc and try to find out if we can write a conversion script / plugin.
