### ISSUE TITLE
add some text how to user binder integration in introduction

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-docs#157]
maybe with image or as  gif that shows where to click

**Comment by tapaswenipathak** [comment]
@greengypsy: can you check if there is existing documentation for this? If not, add and close.

**Comment by timosachsenberg** [comment]
I think @rahul799 might have added a gif... but please double check

**Comment by rahul799** [comment]
Already added https://pyopenms.readthedocs.io/en/latest/installation.html?highlight=binder#try-online.
