### ISSUE TITLE
[GH Actions] PR tests: only convert and test changed RSTs

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#181]
And maybe print the errors in a nicer way.

**Comment by timosachsenberg** [comment]
but we can manually trigger it on all via the extra action right?

**Comment by jpfeuffer** [comment]
The idea is to test all as soon as it is merged to develop without a manual trigger. Something was just not working.

**Comment by timosachsenberg** [comment]
ah that's a good idea.
keeping an additional manual trigger would be still good because after changing OpenMS/pyOpenMS we might also want to run all tests
