### ISSUE TITLE
PyOpenMS getPrecursorSpectrum()

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/pyopenms-docs#224]
Example: Precursor Purity
https://github.com/OpenMS/pyopenms-extra/blob/master/docs/source/datastructures_peak.rst

Currently has a suboptimal way to get the precursor spectrum (this can fail e.g. for mzMLs with MSn). 

https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/KERNEL/MSExperiment.h#L521
MSExperiment has a helper function, which can currently not easily be wrapped in pyopenms (at least to my understanding)
`ConstIterator getPrecursorSpectrum(ConstIterator iterator) const;`

What would be the best way forward here?

**Comment by timosachsenberg** [comment]
I went for now with the simplest solution of providing an index (this case arises frequently if data frames are constructed and one knows the index).

**Comment by tapaswenipathak** [comment]
Any documentation required here?
