### ISSUE TITLE
Add IDFilter example

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-docs#232]
especially how to update groups and protein references

**Comment by rahul799** [comment]
@timosachsenberg can you paste some links for reference or some examples of IDFilter.

**Comment by timosachsenberg** [comment]
Happy to do so. I will post the C++ code as reference:
Not sure if all of those are wrapped, but these are used quite frequently:
Quite a bunch:
- [ ]  https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L134
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L173
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L209
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L372
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L353
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L314
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L402
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L413
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L434
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L467
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L486
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L515
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L540
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L587
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L606
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L622
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L637
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L716
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L747
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L780
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L802
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L881
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L1012
- [ ] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/IDFilter_test.cpp#L1047

**Comment by rahul799** [comment]
Thankyou @timosachsenberg . This helps.
