### ISSUE TITLE
Add class / API documentation 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-docs#246]
To move forward with the automatic API/class documentation, we need to support multi-line comments for methods.
Instead of having only a single line doc string like:
```
  void myfunction(int s) # wrap-doc:This is a doc string
```
we need support for:
```
  void myfunction(int s)
  # wrap-doc:
                #   blabla
                #   -----
                #   blablaba
                #   -----
                #   :param s: bla
```

I think this already works for classes but not for methods.

**Comment by timosachsenberg** [comment]
How this could be done:
- needs to be added to PXDParser in autowrap https://github.com/uweschmitt/autowrap/blob/a33432e9424fbb156b721168cd3f2fcdaf67b682/autowrap/PXDParser.py
- use https://github.com/uweschmitt/autowrap/blob/master/tests/test_pxd_parser.py to test the functionality

**Comment by tapaswenipathak** [comment]
Should @greengypsy or I takeover?

**Comment by jpfeuffer** [comment]
This should be done. See autowrap repository. We reopen if something does not work.
