### ISSUE TITLE
Do not Index function names

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#262]
We have recently added apidocs under apidocs rst.
Unfortunately it adds everything to the index.
I think functions are maybe not needed there.
But I don't know how to pass :noindex: to autosummary such that autodoc uses it for functions.

**Comment by tapaswenipathak** [comment]
Can you write one example?

**Comment by jpfeuffer** [comment]
I think I improved on that by making the apidoc hierarchical.
First modules, then classes, then methods. As separate pages.
Works ok for now.
