### ISSUE TITLE
Make index more prominent

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#263]
Currently it is only reachable by scrolling down on the home page of the documentation I think.
https://pyopenms.readthedocs.io/en/latest/index.html#indices-and-tables

which leads to:
https://pyopenms.readthedocs.io/en/latest/genindex.html

**Comment by tapaswenipathak** [comment]
Where do you think index would be better placed?

**Comment by jpfeuffer** [comment]
It is available under apidoc with a title in the Sidebar by now.
