### ISSUE TITLE
Get changed files action in test_pr.yml wrong

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#272]
It should ignore rsts in subfolders like _templates !!

**Comment by jpfeuffer** [comment]
see https://github.com/OpenMS/pyopenms-docs/pull/271

where I had to ignore it because the syntax of the action is so bad that I had to give up

**Comment by jpfeuffer** [comment]
@poshul didn't you recently have a look on that action in the OpenMS repo?

**Comment by poshul** [comment]
@jpfeuffer I just updated the get changed file action and limited depth of traversal. Can you double check that this does what you want?

**Comment by jpfeuffer** [comment]
Looks correct. You could test it with a whitespace PR changing files in the normal source/docs folder and templates.
