### ISSUE TITLE
Detect common binder errors automatically

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-docs#276]
Check for common errors:
1. if we can detect automatically if the binder page breaks.
2. if we can trigger regular rebuilds of the notebooks to detect errors in the bindings

**Comment by jpfeuffer** [comment]
We do that. For every push every file.
For every PR only changed files.

**Comment by timosachsenberg** [comment]
just to make sure 1. and 2.?

**Comment by jpfeuffer** [comment]
In theory we should cover the binder functionality in the pyopenms tests. If binder breaks due to outside changes in Openms, then the pyopenms tests were not good enough.

**Comment by jpfeuffer** [comment]
You can try to trigger them from e.g. an Openms action but it will be hard to catch. No one will look in this repo here.

**Comment by timosachsenberg** [comment]
hmm I think we need to find a way to monitor the outcome of these actions.
CDash seems to be a bit restricted in this regards. Maybe we should look for (additional) dashboard
that just shows a traffic light and links back to the action log.

**Comment by jpfeuffer** [comment]
Yes but I am not sure if this tracks cross-repo

**Comment by jpfeuffer** [comment]
And to release Openms more often.
