### ISSUE TITLE
Explicitly import pyOpenMS

### ISSUE THREAD

**Issue by Kastakin** [OpenMS/pyopenms-docs#278]
[Star imports are a bad practice](https://stackoverflow.com/questions/2386714/why-is-import-bad) and should be avoided in the examples proposed in the documentation.

While learning the OpenMS framework I usually imported the package with `import pyopenms as ms`, maybe it's possible to decide on a two letter identifier to import the package. 

I can work on the issue if it's considered worth by everyone and not just me!

**Comment by jpfeuffer** [comment]
Totally agree. And I like `ms`.

**Comment by timosachsenberg** [comment]
good point! agree

**Comment by tjeerdijk** [comment]
Same here. It has always annoyed me that the star import does not make explicit which functions or methods from OpenMS are being used in the examples.

**Comment by tapaswenipathak** [comment]
Should @greengypsy or I takeover this issue?

**Comment by timosachsenberg** [comment]
@Kastakin did you already move forward here? Just checking because I would like to prevent duplicated work if @tapaswenipathak or @greengypsy take over.

**Comment by Kastakin** [comment]
Sorry for the late reply, I'm having a busy month with some university workshops. I think I'll be able to work on the task from the 12th of June forward. 

If you intend to start working on it maybe I can join in later if we coordinate properly!

**Comment by tapaswenipathak** [comment]
On Wed, Jun 1, 2022 at 9:29 PM Lorenzo Castellino
***@***.***> wrote:
>
> Sorry for the late reply, I'm having a busy month with some university workshops. I think I'll be able to work on the task from the 12th of June forward.
>
> If you intend to start working on it maybe I can join in later if we coordinate properly!

Hi Lorenzo! we'll start on 12th June, see you at
https://discord.com/invite/swkxs72CHB.

**Comment by JeeH-K** [comment]
@timosachsenberg 
Could you help me understand this issue a bit closer? We just want to change all the example codes in the pyopenms-docs repository as `import pyopenms as ms` from `from pyopenms import *`?

**Comment by jpfeuffer** [comment]
Yes, either this and then use `oms.MSExperiment()` etc.
Or just import what is needed (`from pyopenms import MSExperiment, FileHandler, ...`)

**Comment by tjeerdijk** [comment]
My preference would be the first option to make explicit what is part of pyOpenMS. Explicitly:

import pyopenms as poms
poms.MSExperiment()

(Other abbreviations than poms are fine too, I like poms)

On 8. May 2023, at 16:46, Julianus Pfeuffer ***@***.******@***.***>> wrote:



Yes, either this and then use oms.MSExperiment() etc.
Or just import what is needed (from pyopenms import MSExperiment, FileHandler, ...)

**Comment by JeeH-K** [comment]
Thanks for the clarifications! My vote for abbreviation is on poms ;) 
Since I'm quite occupied this week, I'll start working on it in the next sprint. Hope that's okay.

**Comment by timosachsenberg** [comment]
haha that is funny - I personally used oms so far ( I guess because it sounds more like a mantra (and poms like the small town Boms ;) )
