### ISSUE TITLE
Pandas export tutorial has warnings

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#279]
No idea how it was merged with failing tests but it always fails ipynb conversion. See latest PRs.

**Comment by jpfeuffer** [comment]
Something in the CSV tables probably

**Comment by axelwalter** [comment]
Just checked the table formatting in the rst files, there were some inconsistencies with tabs and spaces. Let's see if the resolves the issue.

**Comment by jpfeuffer** [comment]
yes, better:

Warning:  Reference not found for 'Key "q86uq0"' at pandas_df_conversion.rst_chunk line 1 column 17
Warning:  Reference not found for 'Key "p61313"' at pandas_df_conversion.rst_chunk line 1 column 11

**Comment by jpfeuffer** [comment]
But at least it works now.

**Comment by timosachsenberg** [comment]
todo: try to debug what is going on here
