### ISSUE TITLE
pyOpenMS docs doesn't have an FAQ page

### ISSUE THREAD

**Issue by greengypsy** [OpenMS/pyopenms-docs#281]
Currently, the pyOpenMS docs doesn't have an FAQ page. The FAQs currently reside in the [wiki](https://github.com/OpenMS/OpenMS/wiki/Developer-FAQ). I think the pyOpen FAQs from this section should be moved to pyOpenMS docs.

**Comment by jpfeuffer** [comment]
Yes please, makes sense.
