### ISSUE TITLE
Add tutorial how to generate modified sequences using ModifiedPeptideGenerator

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-docs#289]

**Comment by timosachsenberg** [comment]
e.g., create AASequence object, getModifications "Oxidiation (M)" and then applyVariableModifications

**Comment by sasadshah11** [comment]
@poshul @timosachsenberg  Please provide more details about this task or provide some references so that I may obtain an understanding of how to perform that sprint task.

**Comment by Ayesha-Feroz** [comment]
@poshul  @timosachsenberg  kindly provide more details about this task or provide some references so that I may obtain an understanding of how to perform that task.

**Comment by timosachsenberg** [comment]
Hi,
We want to add a pyopenms tutorial that shows how to use the ModifiedPeptideGenerator class.

The class tests are usually a good starting point to see how they can be used in C++ if there is no other good documentation:
https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/ModifiedPeptideGenerator_test.cpp

What we want now: a pyopenms tutorial on the pyopenms.readthedocs page that shows new users of pyOpenMS how to use this class. Think about someone who never used OpenMS.

What I would do: use this C++ code
https://github.com/OpenMS/OpenMS/blob/d2a64a62e870165558a8eebdf761d5bbaa71fae5/src/tests/class_tests/openms/source/ModifiedPeptideGenerator_test.cpp#L117-L123
and this
https://github.com/OpenMS/OpenMS/blob/d2a64a62e870165558a8eebdf761d5bbaa71fae5/src/tests/class_tests/openms/source/ModifiedPeptideGenerator_test.cpp#L117-L123

and translate it to pyOpenMS to show how modified peptides can be generated.

How do you know how to translate the C++ code to pyOpenMS?

I usually check how we wrap the C++ functions  https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/ModifiedPeptideGenerator.pxd

E.g. here you can see that there exists a wrapper called ModifiedPeptideGenerator https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/ModifiedPeptideGenerator.pxd#L11
and apparently we also wrapped the other functions of the C++ class as python functions with name:
https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/ModifiedPeptideGenerator.pxd#L24-L32
so we probably can already write the python code.

So you probably can do something like:
AASequence sequence = AASequence.fromString("TESTMTESTMTESTR);
mod_names = ["Oxidation (M)"]
mods = ModifiedPeptideGenerator().getModifications(mod_names);
in python to get the map of amino acids to modification objects
and then call applyFixed/VariableModifications(...) with it

I will add Arslan and Kyowon as well to this issue because it will be really useful to learn how the C++ part can be exposed in pyOpenMS.

To try this out, it should be sufficient to install pyopenms from our nightly pypi installer.

**Comment by Arslan-Siraj** [comment]
Thankyou Timo, its seems helpful.

**Comment by timosachsenberg** [comment]
some additional details can also be found here: https://pyopenms.readthedocs.io/en/latest/wrapping_workflows_new_classes.html

**Comment by timosachsenberg** [comment]
Yes please make this work. We really need your help now and in the future.

**Comment by sasadshah11** [comment]
on it.

**Comment by jpfeuffer** [comment]
Hi! @timosachsenberg This class is wrongly wrapped: https://github.com/OpenMS/OpenMS/blob/9f4c98476dbb4d087db74ab15f1edac662f9d8b2/src/pyOpenMS/pxds/ModifiedPeptideGenerator.pxd#LL23C14-L23C14

**Comment by timosachsenberg** [comment]
@Ayesha-Feroz can you check how other static methods are wrapped in pyOpenMS and provide a fix (including correct indentation)?

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/commit/81eb197a6e6a1785a826099c8f7b4d58972bdf7e

**Comment by timosachsenberg** [comment]
what is the state here @Ayesha-Feroz

**Comment by Ayesha-Feroz** [comment]
@timosachsenberg was busy with TAC meetings presentations reports, and research; tried to make time on Sunday but was unsuccessful; will try again next week and report here.

**Comment by jpfeuffer** [comment]
Nothing obvious. Hard to check since the build artifacts are gone.

**Comment by Ayesha-Feroz** [comment]
Upon testing the python code using binder pyopenms versions 3.0, it has been observed that the relevant class might be  is inadequately wrapped or exposed. This implies that the Python environment is not able to access certain aspects of the class's functionality, or the functionality may not operate as expected. Additional analysis is necessary to determine the specific issues with the wrapping or exposure of the class and rectify them accordingly.

**Comment by jpfeuffer** [comment]
> @jpfeuffer I just checked in binder and it seems nothing is wrapped as static function.
> ```
> print(dir(ModifiedPeptideGenerator()))
> ['__class__', '__copy__', '__deepcopy__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '_init_0', '_init_1']
> ```
> 
> any obviously wrong in: https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/ModifiedPeptideGenerator.pxd
> 

It is generated correctly in the latest PRs according to the Jenkins artifacts. Please check that you are using an uptodate version. In this case, check that the wheels are correctly uploaded and binder fetches the latest ones.

**Comment by timosachsenberg** [comment]
is this because we use
https://github.com/OpenMS/pyopenms-docs/blob/master/postBuild
to install pyopenms and we recently renamed the package name from pyopenms-nightly to just pyopenms?
I can fix that

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/pyopenms-docs/pull/386

**Comment by timosachsenberg** [comment]
k I think the version should be up to date... maybe @Ayesha-Feroz can double check in binder?

**Comment by Ayesha-Feroz** [comment]
<img width="1512" alt="upload" src="https://user-images.githubusercontent.com/94114994/236173079-295ef47d-5e2e-4332-9bfb-8bcc58517afa.png">

**Comment by Ayesha-Feroz** [comment]
<img width="1512" alt="upload" src="https://user-images.githubusercontent.com/94114994/236173417-455a8feb-1a13-4e0f-b8ba-6c19b08e42be.png">

**Comment by timosachsenberg** [comment]
update?

**Comment by Ayesha-Feroz** [comment]
https://github.com/OpenMS/pyopenms-docs/pull/390/commits/db4eaaeff749a246c728ab25104053307f545d66
updated code and Timo comments.
trying to test code on binder and facing difficulties in accessing Binder from both my Windows and Mac machines. Specifically, I am only able to successfully connect to Binder once in a  weekend, and subsequent attempts to access it have been unsuccessful. Tested it on google collab and facing an error, talked to Timo he said it might be broken because our Python server seems to be offline. Now I will manually install the wheel and test the code.
