### ISSUE TITLE
Expand theoretical spectrum generation tutorial

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-docs#291]
- introduce b and y ions and how they are formed
- talk about add prefix ions and precursor ions option (e.g., to explain how many ions are generated)

**Comment by JeeH-K** [comment]
Is it going to be included on readthedocs? @timosachsenberg

**Comment by timosachsenberg** [comment]
Hi. Yeah it would be great to look for the appropriate section in the readthedocs documentation (I think we already cover spectrum generation) and expand that a bit.

**Comment by JeeH-K** [comment]
https://openms.readthedocs.io/en/latest/openms-applications-and-tools/visualize-with-openms/views-in-toppview.html#d-view
Here's the only place that talks about the theoretical spectrum generation. I'll try to add an extra page for this.

**Comment by timosachsenberg** [comment]
https://pyopenms.readthedocs.io/en/latest/search.html?q=TheoreticalSpectrumGenerator&check_keywords=yes&area=default

**Comment by JeeH-K** [comment]
I'll expand here
https://pyopenms.readthedocs.io/en/latest/hyperscore.html?highlight=theoretical%20spectrum#generate-a-theoretical-spectrum

**Comment by timosachsenberg** [comment]
e.g.  or here https://pyopenms.readthedocs.io/en/latest/theoreticalspectrumgenerator.html?highlight=TheoreticalSpectrumGenerator#y-ion-spectrum
but please decide for yourself

**Comment by JeeH-K** [comment]
A little bit off-topic maybe, but curious: 
https://pyopenms.readthedocs.io/en/latest/theoreticalspectrumgenerator.html?highlight=TheoreticalSpectrumGenerator#y-ion-spectrum
"plot_spectrum" is implemented in pyopenms? It doesn't work with me

**Comment by JeeH-K** [comment]
https://github.com/OpenMS/pyopenms-docs/issues/338
I guess it doesn't correspond to the released pyopenms

**Comment by timosachsenberg** [comment]
@matteopilz

**Comment by JeeH-K** [comment]
https://github.com/OpenMS/pyopenms-docs/pull/341

**Comment by JeeH-K** [comment]
Cannot agree more. I'd prefer the doc to correspond to the released version, not the nightly/develop version.

**Comment by JeeH-K** [comment]
Trying to solve this issue before working on doc: #6701

**Comment by jpfeuffer** [comment]
What to display as default is a different issue which should be discussed separately. The linked issue is about the visibility of the version switch.

**Comment by jpfeuffer** [comment]
By default I mean where pyopenms.readthedocs.io redirects to.
