### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by vcoyne1** [OpenMS/pyopenms-docs#302]
I have tried a number of approaches to install pyopenms on a Win 11 machine. No matter what I do, I get the following error message: 

ERROR: Could not find a version that satisfies the requirement pyopenms (from versions: 2.3.0.linux-x86_64, 2.3.0.1.linux-x86_64, 2.3.0.2.linux-x86_64, 2.3.0.3.linux-x86_64)
ERROR: No matching distribution found for pyopenms

I would greatly appreciate assistance with this issue.

Thanks,
vcoyne

**Comment by jpfeuffer** [comment]
Hi!

Why are you trying to install pyopenms 2.3?
This old version is neither supported nor available for Windows.

**Comment by vcoyne1** [comment]
> Hi!
> 
> Why are you trying to install pyopenms 2.3? This old version is neither supported nor available for Windows.

Hi,
 I'm not - I get the error messages after running the script "pip install pyopenms".

**Comment by jpfeuffer** [comment]
What python and pip version?

**Comment by vcoyne1** [comment]
I'm running python 3.10.7 and pip 22.2.2 on a Win64 machine

**Comment by jpfeuffer** [comment]
Ah, I see. Python 3.10 is only supported in the nightly versions, for which we do not have a PyPi server yet (@poshul @timosachsenberg).

See the files listed for every version on the public PyPi server: https://pypi.org/project/pyopenms/2.7.0/#files

For nightly installation, please see https://pyopenms.readthedocs.io/en/latest/installation.html#nightly-ci-wheels

Nightly builds' availability is subject to successful builds in our CI.

**Comment by vcoyne1** [comment]
So it seems that I need to roll back Python to 3.9 to install pyopenms-2.7.0-cp39-cp39-win_amd64.whl. If this works, what will happen if I then re-install Python 3.10?

**Comment by jpfeuffer** [comment]
You can have multiple python versions installed but pyopenms (stable 2.7) will only be usable and installable within the python 3.9 version.

**Comment by vcoyne1** [comment]
@jpfeuffer Thank you so much for your assistance with this. The problem has been resolved.
