### ISSUE TITLE
Create issue templates for different use cases.

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#305]
E.g. doc issue
code issue etc.

Always require the OS, version, py version, command/code tried as basic information.

**Comment by Happy-reindeer007** [comment]
Hi there! 👋 I’m interested in this issue. Could you please assign me? 😄

**Comment by jpfeuffer** [comment]
Sure! You can make a first suggestion as a PR (based on the short issue description) and we discuss what could be added.

**Comment by Happy-reindeer007** [comment]
Hi, sorry for the delay, I’ve been a bit busy the last few days 😞 I’ll still be up for it if it’s OK with you, I’ll try to do it this weekend.

Thank you for your understanding
