### ISSUE TITLE
Replace flake with flakeheaven for linting

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#311]
flakeheaven can be used directly with md,rst,ipynb. Currently we are only testing pure py files.
Probably quickest to lint the rst right away but more accurate with the ipynbs.
I don't care which one we do.

**Comment by jpfeuffer** [comment]
And: Make linting actually fail, when it finds something to fix. It currently does not fail.

**Comment by matteopilz** [comment]
I have looked into flakeheaven and it looks like there are two options:

1. Include this one https://github.com/sailingpalmtree/reviewdog-flakehell-action. I have tried shortly and it produces an error. Also, it doesn't seem to have a lot of activity going on in the repo.
2. Make a GitHub action ourselves with https://github.com/flakeheaven/flakeheaven. This seems like a bigger effort, but the output provided is compatible with GitLab CI, so maybe it's possible to adapt it to GitHub more easily.

Any thoughts on this?

**Comment by poshul** [comment]
I spent a bit of time looking at the existing action. I think it's probably
a better use of time to make a new action ourselves.

**Comment by jpfeuffer** [comment]
Yes. It should be straightforward. We do not need an "action" per see but our own script, yes.
It should be just a few lines though.
- Add a pyproject toml to the repo. Can be any config or the default, I don't care. I prefer line width 120 if this exists.
- Install flakeheaven probably via pip or conda
- Run on all rsts or **better** only the ones changed (see the already existing "files-changed") action
- I vote for auto-applying and re-commiting the changes. Should be straightforward in python.
