### ISSUE TITLE
Update everything for new nightly pypi repo

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#313]
**Describe the problem you encountered**

This includes documentation on how to install nightly versions.
As well as all CI yml files. Plus our binder initialitazion script.

**Comment by poshul** [comment]
I think #340 addresses all of these. @jpfeuffer can you check to see if I missed anything?

**Comment by timosachsenberg** [comment]
which CI stuff did you update?
e.g. I only looked into one but this still uses wget to get nightly pyopenms https://github.com/OpenMS/pyopenms-docs/blob/master/.github/workflows/test-pr.yaml#L39
