### ISSUE TITLE
Implement retention strategy for nightly pypi repo

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#318]
Just so we do not run out of space. (e.g. delete after 30 days).
Simple cron job would be enough, I guess. Maybe there is something built-in.
Needs to be documented and easily changeable by team members.

**Comment by timosachsenberg** [comment]
@poshul can you take a look here?

**Comment by poshul** [comment]
Will do. I'm in Mexico through Wednesday, and will take a look when I get
back.

Sam

On Friday, December 9, 2022, Timo Sachsenberg ***@***.***>
wrote:
> @poshul can you take a look here?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci5.googleusercontent.com/proxy/lPVDRkctDqfHTTKH-OfT0zPDXJe3XNn0m8az6XAI7x_rJV0JAR8-L71Gb0dwYCJBfPAMtDDoVR7k5Q7TxR4iyJwCHWnBOEz2_zzkW5ycwBoSt-9DvXmNiJucPPOlQU-shL5RcnqHFdhA7TRsOk_O_BI03qkJA_83ASQ6nnO-JilN_MBxhawRFOk3uK9Q6e-o95GBPnPH4CC-ZOCtpsltw5TLiqukVegqqXo8UztP1WHKh8sbmg=s0-d-e1-ft#https://github.com/notifications/beacon/AABD3C7QT4QVE4HT3PVWHADWMM7AHA5CNFSM6AAAAAASZM2TKKWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSQEGKMA.gif>Message
ID: ***@***.***>

**Comment by jpfeuffer** [comment]
done
