### ISSUE TITLE
Nightly pypi repo not working

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#323]
**Describe the problem you encountered**
```
gitpod /workspace/quantms (dev) $ python3 -m pip install --index-url https://pypi.cs.uni-tuebingen.de/simple/ pyopenms-nightly==3.0.0
Looking in indexes: https://pypi.cs.uni-tuebingen.de/simple/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.cs.uni-tuebingen.de', port=443): Read timed out. (read timeout=15)")': /simple/pyopenms-nightly/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.cs.uni-tuebingen.de', port=443): Read timed out. (read timeout=15)")': /simple/pyopenms-nightly/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.cs.uni-tuebingen.de', port=443): Read timed out. (read timeout=15)")': /simple/pyopenms-nightly/
```
**To Reproduce**

**What should be happening**

**Screenshots**

**System information:**
 - OS:
 - OS Version:
 - Python version:
 - pyopenms version:
 - How did you install pyopenms? Please cross a box with an X.
     - [ ] conda::bioconda: Specify your conda/mamba command and/or your environment with `conda list`.
     - [ ] conda::openms: Specify your conda/mamba command and/or your environment with `conda list`.
     - [ ] pip
     - [ ] nightly wheel
     - [ ] built from source
 

**Additional context**

**Comment by PierreSnell** [comment]
With [poetry](https://python-poetry.org/docs/) (or via curl): 
```
[tool.poetry.dependencies]
pyopenms = [
    {url="https://pypi.cs.uni-tuebingen.de/simple/pyopenms-nightly/pyopenms_nightly-3.0.0.dev20221215-cp39-cp39-macosx_10_9_x86_64.whl", optional=true, markers="python_version ~= '3.9' and sys_platform == 'darwin'"},
    {url="http://pypi.cs.uni-tuebingen.de/packages/pyopenms_nightly-3.0.0.dev20221215-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", optional=true, markers="python_version ~= '3.9' and sys_platform == 'linux'"},
    {url="https://pypi.cs.uni-tuebingen.de/simple/pyopenms-nightly/pyopenms_nightly-3.0.0.dev20221215-cp39-cp39-win_amd64.whl", optional=true, markers="python_version ~= '3.9' and sys_platform == 'win32'"}
]
```

I can reach the page https://pypi.cs.uni-tuebingen.de/simple/pyopenms-nightly/ in a browser. 

However, when trying to download any of the `.whl` files, I got asked for a username and password... 
Same for poetry that returns a 401 unauthorized error when trying to use it as above. 

Without this authentication everything should be working nicely. 

Hope it helps. 
Have a nice day

**Comment by poshul** [comment]
I'm going to update the Docker image to a newer version of the PyPiServer and debug from there. @PierreSnell I will see what I can change to not require auth for download.

**Comment by jpfeuffer** [comment]
Done!

**Comment by poshul** [comment]
@PierreSnell Excellent timing, we are actually working on that in our current sprint (see https://github.com/OpenMS/OpenMS/issues/6184). It should be ready to go within the next week.
