### ISSUE TITLE
Overwritten/aliased classes not documented correctly

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#326]
**Describe the problem you encountered**
See MSExperiment. It is aliased by MSExperimentDF from _dataframes and then overwritten.

See https://stackoverflow.com/questions/38765577/overriding-sphinx-autodoc-alias-of-for-import-of-private-class
and the linked https://github.com/slundberg/shap/blob/6af9e1008702fb0fab939bf2154bbf93dfe84a16/docs/conf.py#L380-L394

on how to fix this.

**Comment by timosachsenberg** [comment]
@matteopilz would be great if you could fix it our check-out and report some details

**Comment by jpfeuffer** [comment]
No, if you are not monkey-patching stuff in pure python anymore, it won't be needed.

**Comment by timosachsenberg** [comment]
k then let's close this for now
