### ISSUE TITLE
Changed files still not working correctly!

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#343]
**Describe the problem you encountered**

Bugs were introduced in #325 because changed files never finds anything.

**Comment by matteopilz** [comment]
Can you be more specific with changed files never finds anything?

**Comment by jpfeuffer** [comment]
This action:
https://github.com/OpenMS/pyopenms-docs/blob/master/.github/workflows/test-pr.yaml#L21

Check the last PRs and you will see that it never tests anything.

Also check the other workflows that use this action.

**Comment by timosachsenberg** [comment]
I don't see anything in Matteos PR that could crash it. @poshul any insight? Maybe this should be fixed before the next sprint as we otherwise can't close the outstanding PRs etc.?

**Comment by poshul** [comment]
> I don't see anything in Matteos PR that could crash it. @poshul any insight? Maybe this should be fixed before the next sprint as we otherwise can't close the outstanding PRs etc.?

I'll take a look

**Comment by jpfeuffer** [comment]
Matteos PR introduced errors in the code. Not in the action.
It introduced errors *because* the action was not working.

**Comment by poshul** [comment]
@jpfeuffer  can you check https://github.com/OpenMS/pyopenms-docs/pull/350 the change there fixed the action in my demo cases.

**Comment by poshul** [comment]
fixed in #350.

**Comment by jpfeuffer** [comment]
Still not working! #357

**Comment by poshul** [comment]
Hmm, at least its a different error this time! I'll take a look

**Comment by poshul** [comment]
https://github.com/OpenMS/pyopenms-docs/actions/runs/4253340667/jobs/7398075580 ran fine
https://github.com/OpenMS/pyopenms-docs/actions/runs/4253340641/jobs/7398075312 failed. Pretty sure this is because of https://github.com/tj-actions/changed-files/issues/809. I'm bumping to 35

**Comment by jpfeuffer** [comment]
OK seems to work. I hope it stays like that. good find.
