### ISSUE TITLE
Create new logo

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#355]
Create a logo for pyopenms.
Just put a py in front of the normal OpenMS logo. If you want to be fancy, add a pictorial python somewhere. E.g. the S in OpenM**S**.

**Comment by timosachsenberg** [comment]
I think I once created one... let me see if I can dig it up

**Comment by timosachsenberg** [comment]
On the website we use this one:
https://openms.netlify.app/images/pyopenms4.png
not super fancy but has the same colors as the OpenMS logo.

**Comment by timosachsenberg** [comment]
![image](https://user-images.githubusercontent.com/5803621/221191756-f63924fc-51de-44e0-beee-ce73f28e89e0.png)

**Comment by jpfeuffer** [comment]
yes, but then I can just use a colored text.

**Comment by jpfeuffer** [comment]
just ask DallE, Midjourney, SD

**Comment by timosachsenberg** [comment]
you don't have copyright on these afaik

**Comment by jpfeuffer** [comment]
I personally do not care if others reuse it but ok.

**Comment by timosachsenberg** [comment]
![image](https://user-images.githubusercontent.com/5803621/221193991-d2264a69-fefd-4e0a-97c8-5d7be318e6c4.png)
