### ISSUE TITLE
Name issue nightly pypi

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-docs#362]
*Currently* the nightly pyopenms package has a different name! I think we tried to avoid the name clash on the public pypi back then -> I *think* we should name it back, now that we have an own pypi. Probably the logic in the pyopenms build action should be: if release, publish to public pypi AND local, if develop, publish only to local pypi with a .devDATE suffix (following PEP, as we do for conda).

_Originally posted by @jpfeuffer in https://github.com/OpenMS/pyopenms-docs/issues/347#issuecomment-1436790546_

**Comment by poshul** [comment]
What is a good way to test this?

**Comment by jpfeuffer** [comment]
How do you mean?
AFAIR you need to do `pip install pyopenms-nightly`. As soon as you can do `pip install pyopenms` it will be fixed.

**Comment by timosachsenberg** [comment]
quick questions if someone already knows when setting up the action:

how to change the package name so it can be installed via pyopenms?

https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/pyopenms-wheels.yml#L479-L494

**Comment by timosachsenberg** [comment]
ah got it: https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/setup.py#L44

**Comment by jpfeuffer** [comment]
Can you give this change a quick thought, too? Do you see a reason to include the nightly in the name instead of the version?

**Comment by timosachsenberg** [comment]
Hmm I don't see a reason why removing nightly could lead to trouble here.
I have to admit that I don't know if anything depends on how this string needs to be formated.
E.g. if some strange ambiguities arise (latest stable vs latest nightly).

**Comment by jpfeuffer** [comment]
Did you test? Did you check the pyopenms actions? Please link the according PR here, if so.

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/pyopenms-wheels.yml

see:
https://pypi.cs.uni-tuebingen.de/simple/pyopenms/

![image](https://user-images.githubusercontent.com/5803621/224079659-949144d3-2721-4c39-84cf-030afdedafe1.png)

![image](https://user-images.githubusercontent.com/5803621/224079773-e57d545d-6581-4183-b9a6-42235bdb62b8.png)

**Comment by jpfeuffer** [comment]
Thanks a lot!!

**Comment by jpfeuffer** [comment]
Not changed in environment.yml..

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/pyopenms-docs/pull/386

**Comment by timosachsenberg** [comment]
where else?

**Comment by jpfeuffer** [comment]
Should be all now.
