### ISSUE TITLE
Verbosity level

### ISSUE THREAD

**Issue by PierreSnell** [OpenMS/pyopenms-docs#375]
**Describe the problem you encountered**
PyOpenMS is logging too much text for a production library and there is no way to reduce the verbosity. 

**To Reproduce**
1. Load an experiment
2. Run mass trace detection or elution peakdetection or similar algorithms
3. See : 
```
Progress of 'mass trace detection':
-- done [took 0.03 s (CPU), 0.02 s (Wall)] -- 
Progress of 'elution peak detection':
-- done [took 0.08 s (CPU), 0.02 s (Wall)] -- 
Progress of 'assembling mass traces to features':
-- done [took 0.04 s (CPU), 0.02 s (Wall)] -- 
```

I'm converting thousands of files and I got all of the output from pyopenms where my logging get drown in the rest. 

**What should be happening**
Having a handle on the logger so we can do something like : 
```python
import logging
logging.getLogger("PyopenmsLoggerName").setLevel(ERROR)
```
or something similar like `from pyopenms import setDebugLevel; setDebugLevel(ERROR)`

**System information:**
 - OS: Linux
 - OS Version: 6.2.6
 - Python version: 3.9 or 3.10
 - pyopenms version: latest (pypi latest build)
 - How did you install pyopenms? Please cross a box with an X.
     - [x] nightly wheel from pyopenms private pypi repo

**Comment by jpfeuffer** [comment]
Can be done with
`pyopenms.LogConfigHandler().setLogLevel("INFO")` or any other level now.

Note there are still some limitations:
https://github.com/OpenMS/OpenMS/issues/6827
