### ISSUE TITLE
Wheel/Packages server is returning 503. 

### ISSUE THREAD

**Issue by PierreSnell** [OpenMS/pyopenms-docs#395]
```
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.41 (Ubuntu) Server at pypi.cs.uni-tuebingen.de Port 443
```

The server that hosts the wheels (`https://pypi.cs.uni-tuebingen.de/packages`) to install the nightly ones (version 3.0) seems down since thursday last week.  

The alternative would be to install from source but compiling OpenMS on all my machines would not be a feasible solution for me. 

Thanks in advance for any help.

**Comment by poshul** [comment]
Hi @PierreSnell the server had some hiccups, but should be back up now. Can you let me know if it's working for you?

**Comment by PierreSnell** [comment]
Hello @poshul, 

Yes, it's been good for the last few weeks :) 
Thanks a lot, 
Have a good day
