### ISSUE TITLE
Expand spectrum normalization tutorial

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-docs#418]
Add images and maybe some extra explanations / examples to:
https://pyopenms.readthedocs.io/en/latest/user_guide/spectrum_normalization.html

**Comment by Ayesha-Feroz** [comment]
@timosachsenberg  Let me know if anything else needs to be added for this sprint task. Thanks https://github.com/OpenMS/pyopenms-docs/commit/cae748a47938f4cf87967fc001874b78bb7f1b77[
](https://github.com/OpenMS/pyopenms-docs/pull/424/commits/fa3e26557c115d9085ceb725469a012881ce4c79)
