### ISSUE TITLE
Revisit and Add spectrum merger tutorial

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-docs#421]
For classical use cases. Review and update https://github.com/OpenMS/pyopenms-docs/pull/265/files

**Comment by KyowonJeong** [comment]
I will go with this one.

**Comment by KyowonJeong** [comment]
Working on it.. I will make a PR soon.

**Comment by timosachsenberg** [comment]
any update here?

**Comment by KyowonJeong** [comment]
In progress. But can be done by tomorrow for sure.
