### ISSUE TITLE
openMS input files

### ISSUE THREAD

**Issue by saassli21** [OpenMS/pyopenms-docs#430]
Hello,
I'm trying to test this tutorial : https://pyopenms.readthedocs.io/en/latest/user_guide/identification_accurate_mass.html
but I can't download the input folder : https://abibuilder.cs.uni-tuebingen.de/archive/openms/Tutorials/Example_Data/Metabolomics/ 
can you please share it here or send it by mail !!

**Comment by timosachsenberg** [comment]
the folder is up again.
Sorry for the inconvenience
