### ISSUE TITLE
How to extract isotope EIC when using FeatureFinder () ?

### ISSUE THREAD

**Issue by grimace9527** [OpenMS/pyopenms-docs#444]
**What is the type of your request?**
- [ ] Unclear

**Include a description of your report**

Hi, 
I am trying to use FeatureFinder to extract feature from a proteomics mzml file. I find that the output.featureXML file only contains the retention time and m/z values of isotopes in each feature. 

Can I obtain the corresponding intensity? (Not only the max intensity, but also the different intensities of different isotopes at different time. ) by FeatureFinder or some class or function else.

**Provide a screenshot, the text or URL of the corresponding documentation page or section**

The demo code I use is:
https://pyopenms.readthedocs.io/en/latest/user_guide/feature_detection.html#feature-detection

**State the documentation version the report is about**

pyopenms 3.1.0

Much THANKS!!!!!

**Comment by jpfeuffer** [comment]
Are you running targeted or untargeted feature extraction?

I have never tried it in python but for *targeted* in C++ you would do:

```python
ffid = FeatureFinderIdentificationAlgorithm()
# set all your params
ffid.run(...) # with your inputs and outputs
chroms = ffid.getChromatograms()
```
IIRC the names/titles/ids of the chromatograms correspond to the sequences of the peptides plus some suffix for the isotope.

**Comment by grimace9527** [comment]
Thanks for your response!
I've noticed that the targeted feature extraction method can extract intensities, but there's some feature that cannot be attributed to any peptide, so the element formula cannot be obtained. Under this circumstance, can the intensities be extracted same as the targeted mode?

**Comment by jpfeuffer** [comment]
For untargeted you can run FeatureFinderMultiplex (without multiplexing), and each feature will have the convex hulls of the mass traces stored (feature.getConvexHulls()
You will need to do an extraction with other functions yourself with that.

**Comment by jpfeuffer** [comment]
Or, you can use the features from untargeted FeatureFinderMultiplex as additional seeds (in addition to the locations of identified peptides) in the targeted FeatureFinderIdentification.
FFID has a seeds parameter.

**Comment by grimace9527** [comment]
But the FeatureFinderIdentification.run() method requires peptides and proteins list as input:

run(self, peptides: List[[PeptideIdentification](https://pyopenms.readthedocs.io/en/latest/apidocs/_autosummary/pyopenms/pyopenms.PeptideIdentification.html#pyopenms.PeptideIdentification)], proteins: List[[ProteinIdentification](https://pyopenms.readthedocs.io/en/latest/apidocs/_autosummary/pyopenms/pyopenms.ProteinIdentification.html#pyopenms.ProteinIdentification)], peptides_ext: List[[PeptideIdentification](https://pyopenms.readthedocs.io/en/latest/apidocs/_autosummary/pyopenms/pyopenms.PeptideIdentification.html#pyopenms.PeptideIdentification)], proteins_ext: List[[ProteinIdentification](https://pyopenms.readthedocs.io/en/latest/apidocs/_autosummary/pyopenms/pyopenms.ProteinIdentification.html#pyopenms.ProteinIdentification)], features: [FeatureMap](https://pyopenms.readthedocs.io/en/latest/apidocs/_autosummary/pyopenms/pyopenms.FeatureMap.html#pyopenms.FeatureMap))

How should I obtain these inputs from untargeted FeatureFinderMultiplex ?
Thanks

**Comment by jpfeuffer** [comment]
You need to use the overload with the seeds parameter:
https://pyopenms.readthedocs.io/en/latest/apidocs/_autosummary/pyopenms/pyopenms.FeatureFinderIdentificationAlgorithm.html#:~:text=run(self%2C%20peptides%3A%20List%5BPeptideIdentification%5D%2C%20proteins%3A%20List%5BProteinIdentification%5D%2C%20peptides_ext%3A%20List%5BPeptideIdentification%5D%2C%20proteins_ext%3A%20List%5BProteinIdentification%5D%2C%20features%3A%20FeatureMap%2C%20seeds%3A%20FeatureMap)%20%E2%86%92%20None

and pass empty lists if you really do not have any IDs from a search engine or something.

**Comment by jpfeuffer** [comment]
But to be honest, if you want to do FULLY untargeted, it might be faster to just extract the convex hulls from FFMultiplex yourself with
msexp.get2DPeakDataLong(..)

**Comment by grimace9527** [comment]
Thanks and I think I completely got it. : )
