### ISSUE TITLE
Error when loading pyOpenMS libraries!

### ISSUE THREAD

**Issue by LCLazari** [OpenMS/pyopenms-docs#445]
Everytime I try to import pyopenms in jupyter I get this error:

          **======================================================================
          Error when loading pyOpenMS libraries!
          Libraries could not be found / could not be loaded.
          
          To debug this error, please run ldd (on linux), otool -L (on macOS) or dependency walker (on windows) on 
          
          C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopenms\pyopenms*.so
          
          ======================================================================**

It was working fine, but then I decided to work in a jupyter notebook file while I was working on another project in VSCode that was importing pyopenms. For a while the library stopped working on both, but it eventually worked again on VSCode, however this error still persists in jupyter. 
I tried to uninstall/install everything (including VSCode and Jupyter), but nothing worked.

I also get this warning: 

      **C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopenms\__init__.py:41: UserWarning: Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopenms\share/OpenMS) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopenms\share/OpenMS).
        warnings.warn(**

and this ImportError:

      **ImportError: DLL load failed while importing _pyopenms_1: Uma rotina de inicialização da biblioteca de vínculo dinâmico (DLL) falhou.**

**System information:**
 - OS: Windows 
 - OS Version: 11
 - Python version: 3.11.2
 - pyopenms version: 3.2.0
 - How did you install pyopenms? Please cross a box with an X.
     - [ ] conda::bioconda: Specify your conda/mamba command and/or your environment with `conda list`.
     - [ ] conda::openms: Specify your conda/mamba command and/or your environment with `conda list`.
     - [X] pip
     - [ ] nightly wheel
     - [ ] built from source

**Comment by timosachsenberg** [comment]
This bug should be resolved in the newest version.

**Comment by jpfeuffer** [comment]
For now, please try to import pyopenms as the very first library. But yes, should be fixed in the newest version.
